CREATE EXTENSION statsd;
SELECT statsd.increment_counter('localhost', 8125, 'test-counter-1');
SELECT statsd.increment_counter('localhost', 8125, 'test-counter-1');
SELECT statsd.increment_counter('localhost', 8125, 'test-counter-1');
SELECT statsd.increment_counter('localhost', 8125, 'test-counter-1');
SELECT statsd.increment_counter('localhost', 8125, 'test-counter-1');
SELECT statsd.increment_counter('localhost', 8125, 'test-counter-1');
SELECT statsd.increment_counter('localhost', 8125, 'test-counter-1');
SELECT statsd.set_gauge('localhost', 8125, 'test-gauge', 98);
DROP EXTENSION statsd;
